language: rust
rust:
  - nightly
  - 1.0.0-beta.4
notifications:
  email:
    recipients:
      - filipe@codinghighway.com
  irc:
    channels:
      - "irc.mozilla.org#rust-config"
      - "irc.mindforge.org#codinghighway"
